//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuzzfeedQuiz
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAnswer
    {
        public int AnswerID { get; set; }
        public string AnswerOne { get; set; }
        public string AnswerTwo { get; set; }
        public string AnswerThree { get; set; }
        public string AnswerFour { get; set; }
        public string AnswerFive { get; set; }
        public int AnsQuizID { get; set; }
    
        public virtual TQuiz TQuiz { get; set; }
    }
}
